### ISSUE TITLE
Feature Scope's init will override puppeteer's options

### ISSUE THREAD

**Issue by geminiyellow** [patheard/cucumber-puppeteer#100]
hi @patheard 

first you set `BrowserScope` in here, everything good.

https://github.com/patheard/cucumber-puppeteer/blob/4d8f3ba8dacb1940afd3f5f01ab68e2ee6f21fad/features/support/config.js#L17

but when goto this line

https://github.com/patheard/cucumber-puppeteer/blob/4d8f3ba8dacb1940afd3f5f01ab68e2ee6f21fad/features/support/config.js#L63

and the first feature in, the featureScope's params are null,

in `init` method,

https://github.com/patheard/cucumber-puppeteer/blob/4d8f3ba8dacb1940afd3f5f01ab68e2ee6f21fad/features/support/scope/FeatureScope.js#L21-L29

see the `this.browserScope` it is `null`,
and the `worldParameters` also empty,
but you use it in `new BrowserScope({ parameters: worldParameters })`,

so i think that is a bug.

**Comment by geminiyellow** [comment]
so, i think you can do something like that:

```diff
- if (featureScope.isNewFeature(currentFeature)) await featureScope.init(currentFeature);
+ if (featureScope.isNewFeature(currentFeature)) await featureScope.init(currentFeature, this.worldParameters);
```

```diff
- async init(currentFeature) {
+ async init(currentFeature, worldParameters) {
```

**Comment by patheard** [comment]
Ah, nice catch.  I like your solution - should have a PR for it soon.  Thanks!
