### ISSUE TITLE
maybe you should change clickElement's promise order 

### ISSUE THREAD

**Issue by geminiyellow** [patheard/cucumber-puppeteer#101]
in here

https://github.com/patheard/cucumber-puppeteer/blob/4d8f3ba8dacb1940afd3f5f01ab68e2ee6f21fad/features/support/action/clickElement.js#L10-L13

i write my feature test like that:

```
And I click the button "[type='submit']" and wait for the element "#vue-app"
```

and the test will block, finally down by timeout, 
but when i change the promise order, everything is good.

could you tell me why?

**Comment by geminiyellow** [comment]
opps, i found that:

https://github.com/GoogleChrome/puppeteer/issues/3347

**Comment by patheard** [comment]
Yeah, I've run into this problem as well.  For a while, I did change to use `$eval`:

```javascript
await Promise.all([ 
     this.page.waitForSelector(waitForSelector), 
     page.$eval(selector, elem => elem.click())
 ]); 
```
 But it worked inconsistently for other people.

Out of curiosity, do you have an click handlers on your `[type='submit']`, or is it a pure HTML submit?  The reason I ask, is because I have seen cases where javascript event handlers don't get initialized before the tests run, which causes the tests to block.  I've fixed that in the past with a wait action before the click

```gherkin
When  I wait for 2 second
And   I click the button "[type='submit']" and wait for the element "#vue-app"
```

**Comment by patheard** [comment]
Also, I'm surprised changing the order in `Promise.all` fixes it for you, but if it does, and all the unit tests still pass, feel free to submit a PR with the change :)

**Comment by geminiyellow** [comment]
oh, sorry @patheard , the order in `Promise.all` is not the reason. 
sometime it working but sometime it not.
and i did `waitForNavigation` still not working.
maybe it is puppeteer's bug ...

**Comment by geminiyellow** [comment]
i clean up all cache, the `waitFor` working. 
and in my web app, i have to wait > 0.3s, 
really suck.

**Comment by patheard** [comment]
Something else that might work for you is if your app adds a CSS class once all the javascript is finished loading.  If it does, you could do something like:

```gherkin
Scenario: Waiting for a selector after loading a page
    When  I open the url "http://someurl.com"
    And   I wait for element ".js-finished"
```

**Comment by geminiyellow** [comment]
↑ no, i have tried it before, but not working.
