### ISSUE TITLE
Can't use `this.attach`

### ISSUE THREAD

**Issue by hjvvoorthuijsen** [patheard/cucumber-puppeteer#109]
In my testing setup I like to output detailed results in the command line. For that I normally use attachments to make sure the results appear on the right spot in the command line.

With your setup I can't use `this.attach` anymore because you don't expose that in your world constructor. Is it an idea to expose `this.attach` as well.

Something like:

```js
constructor(args){
    this.browser = null;
    this.config = null;
    this.page = null;
    this.worldParameters = args && args.parameters ? args.parameters : {};
    this.attach = args && args.attach ? args.attach : null;
}
```

**Comment by patheard** [comment]
I like that idea - let me take a look at making the change.

**Comment by patheard** [comment]
@hjvvoorthuijsen let me know if the change I just merged in does the trick.  It took a bit longer than expected because I also had to dig into my PrettyFormatter class to figure out why it wasn't outputting the attachments.

**Comment by hjvvoorthuijsen** [comment]
@patheard  I tested it out and it works like a charm, thanks!

Any Idea on when you publish this to NPM? Don't want to push, but I kind of need this feature :innocent: 
In the meantime I'll just install directly from github :+1:

**Comment by patheard** [comment]
Just published a new version to NPM 😉

**Comment by hjvvoorthuijsen** [comment]
Awesome, thanks again!
