### ISSUE TITLE
Testing wont work with v1.0.16 but works with v1.0.15

### ISSUE THREAD

**Issue by psahindrakar** [patheard/cucumber-puppeteer#153]
I have recently started working with cucumber and puppeteer. Came across the library. I just wanted to give it a try. 

First I tried the example project at `https://github.com/patheard/test-cuke`. It works as-is out of the box. 

I then tried to create my own individual project. I tried installing cucumber-puppeteer with `npm install cucumber-puppeteer` and in package.json it installed `^1.0.16` which is the latest release. However `npm test` fails with an error.

The example project `https://github.com/patheard/test-cuke` will not work as well with 'v1.0.16'. 

I tried to check more details for the same and I found out that the `https://github.com/patheard/test-cuke` is still using `v1.0.15` (package.lock file has it) which happens to work properly. When a version is switched to `v1.0.16` there seem to be some issues with the test, which I thought was weird. 

Following is the print screen when I tried to run `npm test` :
![Screenshot from 2020-05-04 18-06-08](https://user-images.githubusercontent.com/7049402/80966986-3f052700-8e33-11ea-913e-1062125e7e01.png)

I could not exactly locate the issue with this. If the example project `https://github.com/patheard/test-cuke` itself could be updated to use with the latest release of cucumber-puppeteer that would also help. 

Any help on this is appreciated. I would also like to take a moment here to thank the contributors for the development efforts on this library. Cheers.

**Comment by patheard** [comment]
Thanks for the bug report - I'll take a look and hopefully have a fix soon.

**Comment by patheard** [comment]
Alrighty - should be fixed now.  The problem was that the test-cuke project was being too permissive in how it included the supporting `.js` files with the `--require` arg.

**Comment by psahindrakar** [comment]
@patheard thank you for the fix. I have also tried it and it works.

I have also been going through the folder and file structure of the cucumber-puppeteer. It is nicely structured and very easy to browse through the code. Thank you for all your efforts. In the near future, I would like to contribute to this project if I come across more steps required which could be useful.

**Comment by patheard** [comment]
Glad to hear it's working 👍 

Not a problem and by all means - if you come across anything that's useful a PR would be appreciated!
