### ISSUE TITLE
support for puppeteer.connect?

### ISSUE THREAD

**Issue by bricas** [patheard/cucumber-puppeteer#164]
Currently [`puppeteer.launch` is used](https://github.com/patheard/cucumber-puppeteer/blob/master/features/support/scope/BrowserScope.js#L24) to start the browser, however, to connect to a remote instance, you need to use `puppeteer.connect`.

Perhaps the existence of `browserWSEndpoint` in the config options can be checked, and if present, use `.connect` over `.launch`?

**Comment by patheard** [comment]
Yeah, I like that idea.  I'd happily look at a PR if you wanted to take a crack at it.  If you don't have the time, I should be able to put something together when I'm back at my computer.

**Comment by bricas** [comment]
I'm not in a great position to do the code change as i'm generally not familiar with the best practices of modern day js coding, however, if you would be open to commenting on the following, then i will put in a PR if you think it's sufficient or can direct me to the best way to go about it.

NB: I wasn't sure why `this.config` never gets set to anything in `init`, so i've added a new variable to collect the config for now.

```
--- features/support/scope/BrowserScope.js.orig	2020-08-04 16:48:45.777042504 -0300
+++ features/support/scope/BrowserScope.js	2020-08-04 16:16:27.452018636 -0300
@@ -21,7 +21,13 @@
         this.close();
 
         this.config = {};
-        this.browser = await puppeteer.launch({...defaultOptions, ...puppeteerOptions, ...this.worldParameters});
+        let config = {...defaultOptions, ...puppeteerOptions, ...this.worldParameters};
+        if('browserWSEndpoint' in config) {
+            this.browser = await puppeteer.connect(config);
+        }
+        else {
+            this.browser = await puppeteer.launch(config);
+        }
         this.page = await this.browser.newPage();
     }
```

**Comment by patheard** [comment]
What you've got looks pretty good.  I would make a minor tweak like so, which actually fixes a problem that currently exists with the code (namely that `this.config` does look like it's being used :)

```javascript
this.config = {...defaultOptions, ...puppeteerOptions, ...this.worldParameters};
if('browserWSEndpoint' in this.config) {
  this.browser = await puppeteer.connect(this.config);
} else {
  this.browser = await puppeteer.launch(this.config);
}
```

The one bit we'd need to test is how the [BrowserScope.close()](https://github.com/patheard/cucumber-puppeteer/blob/master/features/support/scope/BrowserScope.js#L28) method is working.  Right now it always closes the Chrome instance, but if we're using connect, I think the better approach would be to just [disconnect](https://devdocs.io/puppeteer/index#browserdisconnect) from Chrome.

We could do this by [tweaking the close code](https://github.com/patheard/cucumber-puppeteer/blob/master/features/support/scope/BrowserScope.js#L29-L30) like so:

```javascript
if(this.browser) {
  if('browserWSEndpoint' in this.config) {
    await this.browser.disconnect();
  } else {
    await this.browser.close();
  }  
}
```

Give it a test with the above disconnect code, and if it's working as expected, a PR would be great!  The one catch is that I'll be camping for the next week, so I won't be able to review anything until I'm back.

**Comment by bricas** [comment]
Indeed, that seems to work! My session closes at the end of the feature file.

PR pushed.

I'm off for a week as well. Cheers!

**Comment by patheard** [comment]
Thanks for the PR!  Hope you have a good week off.
