### ISSUE TITLE
Custom Variable (e.g. URL)

### ISSUE THREAD

**Issue by velimd** [patheard/cucumber-puppeteer#172]
I was curious, is there a way to have a custom variable injected. In the example/read-me, you set the url however, what if I wanted to pass an variable which changes its url depending on the environment?

**Comment by patheard** [comment]
Currently there's not a way to have custom variable values per environment, but you could do something pretty similar by changing the content of the project's [`.env` file](https://github.com/patheard/cucumber-puppeteer/blob/master/.env) as you ran tests in different environments.

If your tests were part of a CI/CD pipeline, you could store each environment's .env values in a variable, and then just before running the tests, append the contents of the variable for the environment you're about to test:

```sh
echo $TEST_ENV >> .env
```

Where `$TEST_ENV` had the following contents:

```
URL=https://some.test.url.com
```
