### ISSUE TITLE
Allow for phone emulation on openUrl

### ISSUE THREAD

**Issue by noman3453445345** [patheard/cucumber-puppeteer#85]
Is that something that will be going in or can I send in a PR for this?

**Comment by patheard** [comment]
Here's the way I'm currently emulating mobile devices:

```gherkin
When  I open the url "https://google.com" with user agent "Mobile Safari/537.36"
And   I set the browser viewport to 375px width by 812px height
```

Would this work for you?  If not, I'd happily take a PR for the behavior you're looking for.

**Comment by noman3453445345** [comment]
That should work. Where can I find that function?

**Comment by patheard** [comment]
It depends on how you're using the project.  If you're just forking it and using it as a project template, you can just use it exactly like I did in a `.feature` file.  

As a test, you could clone my project, add a new feature file and put this scenario in it:

```gherkin
Scenario: Phone emulation in testing
  When  I open the url "https://google.com" with user agent "Mobile Safari/537.36"
  And   I set the browser viewport to 375px width by 812px height
  Then  I expect the screenshot of "google-mobile" matches the web page
```

This should fail the first time as it creates the missing reference screenshot, but then on the next run, it should pass since the reference screenshot will exist.

Hope this helps.

**Comment by noman3453445345** [comment]
@patheard I think I am misspeaking. I apologize.

Is there a current `support/action` file to allow for phone emulation or will I have to configure it myself in the `openURL` function?

**Comment by patheard** [comment]
Ah, gotcha.  In that case, yes, the `openUrl` function can accept a `userAgent`: 

https://github.com/patheard/cucumber-puppeteer/blob/master/features/support/action/openUrl.js#L13

This is then configured in this `When` step:

https://github.com/patheard/cucumber-puppeteer/blob/master/features/steps/when.js#L22

Does this answer your question?

**Comment by noman3453445345** [comment]
@patheard Oh, I thought you had to do it via `page.emulate`?

Are you saying I can activate phone emulation mode via user strings now in Puppeteer?

**Comment by patheard** [comment]
To be honest, I didn't even know about the page.emulate function :)

I think that could be a really useful addition to the test framework as a new action!  Any chance you've got time for a PR to add it?

**Comment by noman3453445345** [comment]
Ah got it! I'm on my work git so I'll see if I can submit a PR on my personal GIt account soon enough! :-)

**Comment by patheard** [comment]
Had a bit of time today,  so I added the device emulation.  Thanks for the idea - definitely better than how I was doing it.
