### ISSUE TITLE
page.click vs page.evaluate

### ISSUE THREAD

**Issue by noman3453445345** [patheard/cucumber-puppeteer#86]
It seems that `clickElement` does not work on all cases. I have a regular Ext.js app and I tried on other simple ones,

```
let selector = 'input[name="username"]';

// does NOT work
await page.click(selector); 

// does work
await page.evaluate((selector) => document.querySelector(selector).click(), selector); 
```

Googling around, I am not the first person to solve it using the does work method but should the library here adhere to more verbose standards?

**Comment by patheard** [comment]
That's interesting that the `page.click(selector)` isn't working for you on the Ext.js app.  Is that with the latest version of Puppeteer?  I've noticed that behaviour breaks occasionally as they update Puppeteer/Chrome.

Let me know - at the very least, if updating to the `page.evaluate` method does work consistently and doesn't break anything else, it would be an easy change for this project.

**Comment by patheard** [comment]
@agitperson let me know if this now works as expected for your Ext.js app.

**Comment by noman3453445345** [comment]
It does work. Thank you. :-)
