### ISSUE TITLE
how to change Puppeteer launch options use npm script

### ISSUE THREAD

**Issue by geminiyellow** [patheard/cucumber-puppeteer#97]
hi all, i want to use 

`npm run test` for headless puppeteer
`npm run test:dev` for head puppeteer

could you tell me how to ?

**Comment by patheard** [comment]
Hi, that's a good question.  Currently there isn't a way to do that, but I'm going to work on #98 to add a launch option that will let you do that.

**Comment by patheard** [comment]
@geminiyellow I've added support for this.  You can now use the cucumber-js [`--world-parameters`](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#world-parameters) CLI option to pass [Puppeteer launch options](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions).  In your case, it would look like this:

```javascript
"scripts": {
    "test:":    "npx cucumber-js --format ./features/support/util/PrettyFormatter
    "test:dev": "npx cucumber-js --format ./features/support/util/PrettyFormatter --world-parameters \"{\\\"headless\\\": false}\""
}
```
One note.  If you're also using a `puppeteerOptions` object in `package.json`, the `--world-parameters` will take precedence when launching Puppeteer.

Hope this helps!

**Comment by geminiyellow** [comment]
@patheard good job, thank you!
